package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"dotfiles/installer/units"

	"gopkg.in/yaml.v3"
)

func main() {
	unitsDir, err := os.Getwd()
	if err != nil {
		fatal("cannot get working directory: %v", err)
	}

	allUnits, err := discoverUnits(unitsDir)
	if err != nil {
		fatal("discover units: %v", err)
	}

	sort.Slice(allUnits, func(i, j int) bool {
		return allUnits[i].ID < allUnits[j].ID
	})

	if err := validateDependencies(allUnits); err != nil {
		fatal("validate: %v", err)
	}

	code, err := render(allUnits)
	if err != nil {
		fatal("render: %v", err)
	}

	outPath := filepath.Join(unitsDir, "units_gen.go")
	if err := os.WriteFile(outPath, code, 0o644); err != nil {
		fatal("write: %v", err)
	}

	fmt.Fprintf(os.Stderr, "unitgen: wrote %s (%d units)\n", outPath, len(allUnits))
}

func discoverUnits(unitsDir string) ([]units.Unit, error) {
	entries, err := os.ReadDir(unitsDir)
	if err != nil {
		return nil, err
	}

	var result []units.Unit
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		yamlPath := filepath.Join(unitsDir, entry.Name(), "unit.yaml")
		if _, err := os.Stat(yamlPath); err != nil {
			continue
		}

		data, err := os.ReadFile(yamlPath)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", entry.Name(), err)
		}

		var u units.Unit
		if err := yaml.Unmarshal(data, &u); err != nil {
			return nil, fmt.Errorf("%s: parse yaml: %w", entry.Name(), err)
		}

		if err := u.Validate(); err != nil {
			return nil, fmt.Errorf("%s: %w", entry.Name(), err)
		}

		// Apply defaults.
		for i := range u.Stages {
			if u.Stages[i].ExecutionPlan.Shell == "" {
				u.Stages[i].ExecutionPlan.Shell = "bash"
			}
		}

		// Verify task files exist.
		unitDir := filepath.Join(unitsDir, entry.Name())
		for _, stage := range u.Stages {
			for _, task := range stage.Tasks {
				p := filepath.Join(unitDir, "tasks", task.Name)
				if _, err := os.Stat(p); err != nil {
					return nil, fmt.Errorf("%s: stage %q: task file not found: %s", u.ID, stage.Name, p)
				}
			}
		}
		for name, action := range u.Actions {
			p := filepath.Join(unitDir, "tasks", action.Task)
			if _, err := os.Stat(p); err != nil {
				return nil, fmt.Errorf("%s: action %q: task file not found: %s", u.ID, name, p)
			}
		}

		result = append(result, u)
	}

	return result, nil
}

func validateDependencies(allUnits []units.Unit) error {
	knownIDs := make(map[string]bool, len(allUnits))
	for _, u := range allUnits {
		knownIDs[u.ID] = true
	}

	for _, u := range allUnits {
		for _, stage := range u.Stages {
			for _, task := range stage.Tasks {
				for _, dep := range task.DependsOn {
					if !strings.Contains(dep, ".") && !strings.Contains(dep, "/") {
						if !knownIDs[dep] {
							return fmt.Errorf("unit %q, task %q: unknown dependency %q", u.ID, task.Name, dep)
						}
					}
				}
			}
		}
	}

	return nil
}

func render(allUnits []units.Unit) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, allUnits); err != nil {
		return nil, err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w\n\nraw output:\n%s", err, buf.String())
	}

	return formatted, nil
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "unitgen: "+format+"\n", args...)
	os.Exit(1)
}

var funcMap = template.FuncMap{
	"quote": func(s string) string { return fmt.Sprintf("%q", s) },
}

var tmpl = template.Must(template.New("units_gen").Funcs(funcMap).Parse(`// Code generated by unitgen. DO NOT EDIT.

package units

func init() {
{{- range . }}
	Register(Unit{
		ID:       {{ quote .ID }},
		Name:     {{ quote .Name }},
		Critical: {{ .Critical }},
		Stages: []Stage{
{{- range .Stages }}
			{
				Name: {{ quote .Name }},
				Tasks: []Task{
{{- range .Tasks }}
					{
						Name: {{ quote .Name }},
{{- if .DependsOn }}
						DependsOn: []string{ {{- range $i, $d := .DependsOn }}{{ if $i }}, {{ end }}{{ quote $d }}{{ end -}} },
{{- end }}
					},
{{- end }}
				},
				ExecutionPlan: ExecutionPlan{
					Shell: {{ quote .ExecutionPlan.Shell }},
{{- if .ExecutionPlan.Timeout }}
					Timeout: {{ .ExecutionPlan.Timeout }},
{{- end }}
{{- if .ExecutionPlan.Sudo }}
					Sudo: true,
{{- end }}
{{- if .ExecutionPlan.Retry.MaxAttempts }}
					Retry: RetryPolicy{
						MaxAttempts: {{ .ExecutionPlan.Retry.MaxAttempts }},
						Delay:       {{ .ExecutionPlan.Retry.Delay }},
					},
{{- end }}
				},
			},
{{- end }}
		},
		Actions: map[string]Action{
{{- range $name, $action := .Actions }}
			{{ quote $name }}: {
				Task:        {{ quote $action.Task }},
				Description: {{ quote $action.Description }},
			},
{{- end }}
		},
	})
{{ end -}}
}
`))
