id: dotenv
name: ".env"
stages:
  - name: verify
    tasks:
      - task: verify.sh
  - name: setup
    tasks:
      - task: setup.sh

actions:
  teardown:
    task: teardown.sh
    description: "Reverte este unit"
