id: pacman_conf
name: "pacman.conf"
critical: true
stages:
  - name: verify
    tasks:
      - task: verify.sh
  - name: setup
    tasks:
      - task: setup.sh
        depends_on:
          - sudoers
    executor:
      sudo: true

actions:
  teardown:
    task: teardown.sh
    description: "Reverte este unit"
