// Code generated by unitgen. DO NOT EDIT.

package units

func init() {
	Register(Unit{
		ID:       "claude_code",
		Name:     "Claude Code",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name: "setup.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "claude_mcp",
		Name:     "Claude MCP servers",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"claude_code", "mise"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "directories",
		Name:     "Diretórios",
		Critical: true,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name: "setup.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "dotenv",
		Name:     ".env",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name: "setup.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "flatpak_apps",
		Name:     "Flatpak apps",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"flatpak_repos"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "flatpak_repos",
		Name:     "Flatpak repos (Flathub)",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"packages"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "git_configs",
		Name:     "Git workspace configs",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"directories", "packages"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "gpu_drivers",
		Name:     "GPU drivers",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"packages"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell:   "bash",
					Timeout: 300,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "locale",
		Name:     "Locale/teclado",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name: "setup.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
					Sudo:  true,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "mise",
		Name:     "mise + Node/uv/pnpm",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name: "setup.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell:   "bash",
					Timeout: 300,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "oh_my_posh",
		Name:     "oh-my-posh",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name: "setup.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "packages",
		Name:     "Pacotes (yay)",
		Critical: true,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"yay"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell:   "bash",
					Timeout: 600,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "pacman_conf",
		Name:     "pacman.conf",
		Critical: true,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"sudoers"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
					Sudo:  true,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "services",
		Name:     "Serviços",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"packages"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
					Sudo:  true,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "shell",
		Name:     "Shell (zsh)",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"packages"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
					Sudo:  true,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "stow",
		Name:     "GNU Stow symlinks",
		Critical: false,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"packages"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "sudoers",
		Name:     "NOPASSWD sudoers",
		Critical: true,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name: "setup.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
					Sudo:  true,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})

	Register(Unit{
		ID:       "yay",
		Name:     "yay (AUR helper)",
		Critical: true,
		Stages: []Stage{
			{
				Name: "verify",
				Tasks: []Task{
					{
						Name: "verify.sh",
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell: "bash",
				},
			},
			{
				Name: "setup",
				Tasks: []Task{
					{
						Name:      "setup.sh",
						DependsOn: []string{"sudoers"},
					},
				},
				ExecutionPlan: ExecutionPlan{
					Shell:   "bash",
					Timeout: 300,
				},
			},
		},
		Actions: map[string]Action{
			"teardown": {
				Task:        "teardown.sh",
				Description: "Reverte este unit",
			},
		},
	})
}
